export const ansi = {
  key: {
    tab: "\x09",
    enter: "\x0D",
    escape: "\x1B",
    backspace: "\x7F",
    delete: "\u001b[3~",
    exit: "\x03",
    up: "\x1B[A",
    down: "\x1B[B",
    right: "\x1B[C",
    left: "\x1B[D",
  },

  format: {
    reset: `\x1b[0m`,
    bold: `\x1b[1m`,
    faint: `\x1b[2m`,
    italic: `\x1b[3m`,
    underline: `\x1b[4m`,
    blink: `\x1b[5m`,
    rapid: `\x1b[6m`,
    reverse: `\x1b[7m`,
    conceal: `\x1b[8m`,
    strike: `\x1b[9m`,
  },

  cursor: {
    moveUp: (n: number = 1) => `\x1b[${n}A`,
    moveDown: (n: number = 1) => `\x1b[${n}B`,
    moveRight: (n: number = 1) => `\x1b[${n}C`,
    moveLeft: (n: number = 1) => `\x1b[${n}D`,
    move: (n: number, m: number) => `\x1b[${n};${m}H`,
    save: `\x1b[s`, // position
    restore: `\x1b[u`, // position
    show: `\x1b[?25h`,
    hide: `\x1b[?25l`,
  },

  clear: {
    line: `\x1b[2K`,
    after: `\x1b[0K`,
    before: `\x1b[1K`,
    screen: `\x1b[2J`,
    above: `\x1b[1J`,
    below: `\x1b[0J`,
  },

  foreground: {
    default: "\x1b[39m",
    black: "\x1b[30m",
    red: "\x1b[31m",
    green: "\x1b[32m",
    yellow: "\x1b[33m",
    blue: "\x1b[34m",
    magenta: "\x1b[35m",
    cyan: "\x1b[36m",
    white: "\x1b[37m",
    brightBlack: "\x1b[90m",
    brightRed: "\x1b[91m",
    brightGreen: "\x1b[92m",
    brightYellow: "\x1b[93m",
    brightBlue: "\x1b[94m",
    brightMagenta: "\x1b[95m",
    brightCyan: "\x1b[96m",
    brightWhite: "\x1b[97m",
  },

  background: {
    default: "\x1b[49m",
    black: "\x1b[40m",
    red: "\x1b[41m",
    green: "\x1b[42m",
    yellow: "\x1b[43m",
    blue: "\x1b[44m",
    magenta: "\x1b[45m",
    cyan: "\x1b[46m",
    white: "\x1b[47m",
    brightBlack: "\x1b[100m",
    brightRed: "\x1b[101m",
    brightGreen: "\x1b[102m",
    brightYellow: "\x1b[103m",
    brightBlue: "\x1b[104m",
    brightMagenta: "\x1b[105m",
    brightCyan: "\x1b[106m",
    brightWhite: "\x1b[107m",
  },
}
