export const ascii = {
  ctrlA: "\x01",
  ctrlB: "\x02",
  ctrlC: "\x03",
  ctrlD: "\x04",
  ctrlE: "\x05",
  ctrlF: "\x06",
  ctrlG: "\x07",
  ctrlH: "\x08",
  ctrlI: "\x09",
  ctrlJ: "\x0A",
  ctrlK: "\x0B",
  ctrlL: "\x0C",
  ctrlM: "\x0D",
  ctrlN: "\x0E",
  ctrlO: "\x0F",
  ctrlP: "\x10",
  ctrlQ: "\x11",
  ctrlR: "\x12",
  ctrlS: "\x13",
  ctrlT: "\x14",
  ctrlU: "\x15",
  ctrlV: "\x16",
  ctrlW: "\x17",
  ctrlX: "\x18",
  ctrlY: "\x19",
  ctrlZ: "\x1A",
}
